export { default as genders } from './genders.js';
export { default as maritalStatuses } from './maritalStatuses.js';
export { default as validateZipcode } from './validateZipcode.js';
export { default as validateCPF } from './validateCPF.js';
export { default as formatCPF } from './formatCPF.js';
export { default as calculateCPFDigit } from './calculateCPFDigit.js';
export { default as validateCellphone } from './validateCellphone.js';
export { default as formatCellphone } from './formatCellphone.js';
export { default as validateClient } from './validateClient.js';
